### ISSUE TITLE
trouble running this sample app locally

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-sample-provider#2]
i tried spinning up a local koop instance using this sample yesterday afternoon and didn't have much joy

STR
1. downloaded `ZIP`
```
npm install
node server.js
..
>>cannot find 'koop-osm' / cannot find 'koop-tile-plugin dependencies'
```
2. added the following to the package.json
```
"koop-osm": "~0.0.5",
"koop-tile-plugin": "~1.0.0"
```
3. blew away `node_modules` folder and reran `npm install`
4. reran `node server.js`
```
body-parser deprecated bodyParser: use individual json/urlencoded middlewares node_modules/koop/index.js:19:11
body-parser deprecated undefined extended: provide extended option node_modules/koop/node_modules/body-parser/index.js:85:29
No Github Token in config. This may cause problems accessing data.
No Github Token in config. This may cause problems accessing data.
Listening at http://0.0.0.0:1337/

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/Users/john6251/Downloads/koop-sample-app-master/node_modules/koop/node_modules/kue/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/Users/john6251/Downloads/koop-sample-app-master/node_modules/koop/node_modules/kue/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:486:13)
```

not sure what i'm missing.  originally i thought i'd just borked my Postgres instance, but i fixed it this morning and the behavior's the same.

**Comment by ngoldman** [comment]
Looks like something is requiring a local Redis instance. Hmm..

**Comment by jgravois** [comment]
thanks. got things going by laying down a local redis instance and starting it up. :smile:

**Comment by ngoldman** [comment]
@jgravois not sure that should be a base requirement though

**Comment by chelm** [comment]
Yeah this probably oversight on my part. We moved off using the sample app in koop.dc. I'll take a look and PR what I think it should have by default.

**Comment by jgravois** [comment]
thanks @chelm

just a few other notes.
1. individual resources can be accessed appropriately, but a call to http://localhost:1337 throws
>>Error: No default engine was specified and no extension was provided.
2. the app throws this error (which doesn't seem to cause any harm as i see records in the table i specified in the config)
>>could not connect to postgres { [error: database "osm" does not exist]

**Comment by chelm** [comment]
@jgravios yup, pr coming soon that removes koop-osm, koop-acs, and koop-tiles 

also will ship with a basic config file and I'll fix that engine issue you see.

**Comment by jgravois** [comment]
just realized i logged this issue in the complete wrong place.
